import { 
  Shield, Zap, Lock, GraduationCap, Users, BarChart3 
} from "lucide-react";
import { TimelineItem } from "@/components/ui/radial-orbital-timeline";

export const timelineFeatures: TimelineItem[] = [
  {
    id: 1,
    title: "Student Portal",
    date: "Core Feature",
    content: "A secure hub for students to manage their academic finances independently.",
    category: "Access",
    icon: Shield,
    relatedIds: [2, 5],
    status: "completed",
    energy: 95,
  },
  {
    id: 2,
    title: "Digital Proofs",
    date: "Innovation",
    content: "Upload screenshots for Telebirr/CBE transactions directly from your phone.",
    category: "Payment",
    icon: Zap,
    relatedIds: [1, 3],
    status: "completed",
    energy: 90,
  },
  {
    id: 3,
    title: "Verified Receipts",
    date: "Integrity",
    content: "Automated receipt unlocking only after verified administrator approval.",
    category: "Security",
    icon: Lock,
    relatedIds: [2, 6],
    status: "completed",
    energy: 100,
  },
  {
    id: 4,
    title: "Class Management",
    date: "Organization",
    content: "Efficiently group students and manage academic structures at scale.",
    category: "Structure",
    icon: GraduationCap,
    relatedIds: [5],
    status: "completed",
    energy: 85,
  },
  {
    id: 5,
    title: "Student Directory",
    date: "Management",
    content: "Quickly search, enroll, and manage student profiles in a single click.",
    category: "Data",
    icon: Users,
    relatedIds: [1, 4],
    status: "completed",
    energy: 80,
  },
  {
    id: 6,
    title: "Analytics",
    date: "Insights",
    content: "Live dashboards tracking institution revenue and collection updates.",
    category: "Reporting",
    icon: BarChart3,
    relatedIds: [3],
    status: "completed",
    energy: 92,
  },
];

export const features = [
  {
    icon: Shield,
    title: "Student Portal",
    description: "Secure, role-based access for students to check balances, view payment history, and report digital transactions.",
    color: "from-indigo-500 to-purple-600",
    bgLight: "bg-indigo-50",
    bgDark: "dark:bg-indigo-950/30",
    borderColor: "border-indigo-200 dark:border-indigo-800/50",
    iconColor: "text-indigo-600 dark:text-indigo-400",
  },
  {
    icon: Zap,
    title: "Digital Proofs",
    description: "Support for Telebirr and CBE receipts. Students upload screenshots that admins can verify with a single click.",
    color: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50",
    bgDark: "dark:bg-emerald-950/30",
    borderColor: "border-emerald-200 dark:border-emerald-800/50",
    iconColor: "text-emerald-600 dark:text-emerald-400",
  },
  {
    icon: Lock,
    title: "Verified Receipts",
    description: "Receipts are automatically unlocked and ready for download only after admin verification, ensuring financial integrity.",
    color: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50",
    bgDark: "dark:bg-amber-950/30",
    borderColor: "border-amber-200 dark:border-amber-800/50",
    iconColor: "text-amber-600 dark:text-amber-400",
  },
  {
    icon: GraduationCap,
    title: "Class Management",
    description: "Organize classes and courses effortlessly. Track enrollment counts and manage academic structures from one central hub.",
    color: "from-violet-500 to-indigo-600",
    bgLight: "bg-violet-50",
    bgDark: "dark:bg-violet-950/30",
    borderColor: "border-violet-200 dark:border-violet-800/50",
    iconColor: "text-violet-600 dark:text-violet-400",
  },
  {
    icon: Users,
    title: "Student Directory",
    description: "Maintain a comprehensive student registry. Enroll, search, and manage student profiles with class assignments in seconds.",
    color: "from-blue-500 to-cyan-600",
    bgLight: "bg-blue-50",
    bgDark: "dark:bg-blue-950/30",
    borderColor: "border-blue-200 dark:border-blue-800/50",
    iconColor: "text-blue-600 dark:text-blue-400",
  },
  {
    icon: BarChart3,
    title: "Analytics Dashboard",
    description: "Get an executive snapshot of total revenue, today's collections, and a live report of students with outstanding balances.",
    color: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50",
    bgDark: "dark:bg-rose-950/30",
    borderColor: "border-rose-200 dark:border-rose-800/50",
    iconColor: "text-rose-600 dark:text-rose-400",
  },
];
